# Generated by Django 2.2.7 on 2019-12-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie_name', models.CharField(max_length=200)),
                ('movie_review', models.CharField(max_length=3)),
                ('movie_genere', models.CharField(max_length=50)),
            ],
        ),
    ]
