# Generated by Django 2.2.7 on 2019-12-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0003_movieinfo_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/%Y%m%d'),
        ),
    ]
