# Generated by Django 2.2.7 on 2019-12-03 10:43

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0004_movieinfo_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('year_of_manufacture', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('image', s3direct.fields.S3DirectField(blank=True)),
                ('video', s3direct.fields.S3DirectField(blank=True)),
            ],
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='pictures/%Y%m%d'),
        ),
    ]
