# Generated by Django 2.2.7 on 2019-12-03 11:31

from django.db import migrations, models
import s3direct.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0005_auto_20191203_1613'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Car',
        ),
        migrations.RemoveField(
            model_name='movieinfo_test',
            name='movie_test',
        ),
        migrations.AddField(
            model_name='movieinfo_test',
            name='image',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AddField(
            model_name='movieinfo_test',
            name='name',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='movieinfo_test',
            name='price',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
        migrations.AddField(
            model_name='movieinfo_test',
            name='video',
            field=s3direct.fields.S3DirectField(blank=True),
        ),
        migrations.AddField(
            model_name='movieinfo_test',
            name='year_of_manufacture',
            field=models.CharField(default='SOME STRING', max_length=255),
        ),
    ]
