# Generated by Django 2.2.7 on 2019-12-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0006_auto_20191203_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieinfo_test',
            name='image',
        ),
        migrations.RemoveField(
            model_name='movieinfo_test',
            name='video',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(blank=True, max_length=200, null=True, upload_to='pictures'),
        ),
        migrations.AlterField(
            model_name='movieinfo_test',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movieinfo_test',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movieinfo_test',
            name='year_of_manufacture',
            field=models.CharField(max_length=255),
        ),
    ]
