# Generated by Django 2.2.7 on 2019-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieReview', '0007_auto_20191204_0017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image_url', models.ImageField(blank=True, null=True, upload_to='our_pictures')),
            ],
        ),
        migrations.DeleteModel(
            name='MovieInfo_Test',
        ),
        migrations.AlterField(
            model_name='movieinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures'),
        ),
    ]
